# created by Makefile.kt on 2024-09-20T16:51:20.737268700    
# GOARCH=arm64 GOOS=linux go build -tags lambda.norpc -o ./bin/bootstrap

linux-build:
	GOARCH=amd64 GOOS=windows go build -tags lambda.norpc -o ./bin/bootstrap.exe
	jar cvf bin/gofunctions-1.0.12-SNAPSHOT-schemact-aws-lambda.zip -C bin bootstrap

run:
	go run main.go
     